on: workflow_dispatch
name: deploy-resource-group
jobs:
  prepare-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Login with Service Principal
        run: |
          az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}    
  provision-resources:
    runs-on: ubuntu-latest
    needs: prepare-and-validate
    steps:
      - name : Checkout the repository
        uses: actions/checkout@v3
      - name: List files in the repository
        run: ls -R
      - name: Conduct Terraform init
        run: |
          export ARM_CLIENT_ID=${{ secrets.CLIENT_ID }}
          export ARM_CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
          export ARM_TENANT_ID=${{ secrets.TENANT_ID }}
          export ARM_SUBSCRIPTION_ID=${{ secrets.SUBSCRIPTION_ID }}
          terraform init
      - name: Conduct Terraform fmt
        run: |
          terraform fmt
      - name: Conduct Terraform validate
        run: |
          terraform validate
      - name: Conduct Terraform plan
        run: |-
          terraform plan -out "tfplan"
      - name: Conduct Terraform apply
        run: |-
          terraform apply -auto-approve "tfplan"